const express=require('express'),mongoose=require('mongoose'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),path=require('path'),crypto=require('crypto'),fs=require('fs');
const app=express(),PORT=process.env.PORT||3000,URI=process.env.MONGODB_URI,SECRET=process.env.JWT_SECRET;
if(!URI||!SECRET)throw Error('Set MONGODB_URI and JWT_SECRET in Render.');
const transaction=new mongoose.Schema({id:String,type:String,name:String,detail:String,phone:String,country:String,paymentMethod:String,amount:Number,received:String,status:{type:String,default:'Successful'},createdAt:{type:Date,default:Date.now}},{_id:false});
const userSchema=new mongoose.Schema({name:String,email:{type:String,unique:true,lowercase:true},passwordHash:String,password:String,country:{type:String,default:'Kenya'},verified:{type:Boolean,default:true},currency:{type:String,default:'USD'},dark:{type:Boolean,default:false},balance:{type:Number,default:2450},assets:{type:[Object],default:[{symbol:'USDT',network:'Ethereum',balance:2450},{symbol:'BTC',network:'Bitcoin',balance:0.024},{symbol:'ETH',network:'Ethereum',balance:0.82}]},card:{brand:String,last4:String,expiry:String,name:String,country:String},cryptoWallets:{type:[Object],default:[{asset:'BTC',address:'bc1q••••••••••x7p9'},{asset:'ETH',address:'0x7c•••••••••Ae91'}]},history:[transaction]});
const User=mongoose.model('User',userSchema);app.use(express.json());app.get('/',(req,res)=>fs.readFile(path.join(__dirname,'index.html'),'utf8',(e,html)=>res.type('html').send(e?'Server error':html.replace('</body>','<script src="/flow-ui.js"></script></body>'))));app.use(express.static(__dirname));
const safe=u=>({name:u.name,email:u.email,country:u.country,verified:u.verified,currency:u.currency,dark:u.dark,balance:u.balance,assets:u.assets,card:u.card,cryptoWallets:u.cryptoWallets,history:u.history});const issue=u=>jwt.sign({id:u.id},SECRET,{expiresIn:'365d'});
async function auth(req,res,next){try{let t=req.headers.authorization?.replace('Bearer ','');req.user=await User.findById(jwt.verify(t,SECRET).id);if(!req.user)throw 0;next()}catch{res.status(401).json({message:'Please sign in again.'})}}
app.post('/api/register',async(req,res)=>{try{let {name,email,password,country}=req.body;if(!name||!email||!password||password.length<6)return res.status(400).json({message:'Enter a name, email and 6+ character password.'});if(await User.findOne({email:email.toLowerCase()}))return res.status(409).json({message:'An account already exists with this email. Please sign in.'});let u=await User.create({name,email:email.toLowerCase(),passwordHash:await bcrypt.hash(password,12),country});res.json({token:issue(u),user:safe(u)})}catch{res.status(500).json({message:'Could not create your account. Please try again.'})}});
app.post('/api/login',async(req,res)=>{try{let u=await User.findOne({email:req.body.email?.toLowerCase()});let hash=u?.passwordHash||u?.password;if(!u||typeof hash!=='string'||!await bcrypt.compare(String(req.body.password||''),hash))return res.status(401).json({message:'Incorrect email or password.'});res.json({token:issue(u),user:safe(u)})}catch{res.status(500).json({message:'Could not sign in. Please try again.'})}});
app.get('/api/me',auth,(req,res)=>res.json(safe(req.user)));
app.post('/api/profile',auth,async(req,res)=>{let {name,country,currency,dark}=req.body;if(name)req.user.name=name.trim();if(country)req.user.country=country;if(currency)req.user.currency=currency;if(typeof dark==='boolean')req.user.dark=dark;await req.user.save();res.json(safe(req.user))});
app.post('/api/assets',auth,async(req,res)=>{if(!Array.isArray(req.body.assets))return res.status(400).json({message:'Invalid asset list.'});req.user.assets=req.body.assets.map(x=>({symbol:String(x.symbol||'').slice(0,12).toUpperCase(),network:String(x.network||'').slice(0,30),balance:Number(x.balance)||0,price:Number(x.price)||0,change:Number(x.change)||0})).filter(x=>x.symbol);await req.user.save();res.json(safe(req.user))});
app.post('/api/crypto-wallets',auth,async(req,res)=>{if(!Array.isArray(req.body.cryptoWallets))return res.status(400).json({message:'Invalid wallet list.'});req.user.cryptoWallets=req.body.cryptoWallets.map(x=>({asset:String(x.asset||'').slice(0,12).toUpperCase(),network:String(x.network||'').slice(0,30),address:String(x.address||'').slice(0,120)})).filter(x=>x.asset&&x.address);await req.user.save();res.json(safe(req.user))});
app.post('/api/card',auth,async(req,res)=>{let {brand,last4,expiry,name,country}=req.body;if(!brand||!/^\d{4}$/.test(String(last4))||!expiry)return res.status(400).json({message:'Use card type, last four digits and expiry.'});req.user.card={brand,last4:String(last4),expiry,name:name||req.user.name,country:country||req.user.country};await req.user.save();res.json(safe(req.user))});
app.post('/api/transaction',auth,async(req,res)=>{let {type,amount,name,phone,country,paymentMethod,received}=req.body,amountNumber=Number(amount);if(!['send','crypto','topup','withdraw'].includes(type)||!amountNumber||amountNumber<=0)return res.status(400).json({message:'Enter a valid amount.'});if(type==='send'&&(!name||!phone||!paymentMethod))return res.status(400).json({message:'Enter receiver name, mobile number and payment method.'});if(type==='crypto'&&(!name||!paymentMethod))return res.status(400).json({message:'Enter an address and network.'});if(['send','crypto','withdraw'].includes(type)&&amountNumber>req.user.balance)return res.status(400).json({message:'Insufficient wallet balance.'});if(type==='withdraw'&&!req.user.card)return res.status(400).json({message:'Link a card before withdrawing.'});let t={id:'FS-'+crypto.randomBytes(5).toString('hex').toUpperCase(),type,name:type==='send'?name:type==='crypto'?'Crypto transfer':type==='topup'?'Wallet top up':'Withdrawal to card',phone:type==='send'?phone:'',country:country||'',paymentMethod:paymentMethod||'',detail:type==='send'?`${paymentMethod} · ${country}`:type==='crypto'?`${paymentMethod} · ${name.slice(0,6)}••••${name.slice(-4)}`:type==='topup'?`Added from ${req.user.card?.brand||'linked card'}`:`To ${req.user.card.brand} •••• ${req.user.card.last4}`,amount:type==='topup'?amountNumber:-amountNumber,received,status:'Successful',createdAt:new Date()};req.user.balance+=t.amount;req.user.history.unshift(t);await req.user.save();res.json({user:safe(req.user),transaction:t})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));mongoose.connect(URI).then(()=>app.listen(PORT,'0.0.0.0',()=>console.log('FlowSend running'))).catch(e=>{console.error(e);process.exit(1)});
