const express=require('express'),mongoose=require('mongoose'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),path=require('path'),crypto=require('crypto');
const app=express(),PORT=process.env.PORT||3000,URI=process.env.MONGODB_URI,SECRET=process.env.JWT_SECRET;
if(!URI||!SECRET)throw Error('Set MONGODB_URI and JWT_SECRET in Render.');
const transaction=new mongoose.Schema({id:String,type:String,name:String,detail:String,phone:String,country:String,amount:Number,received:String,status:{type:String,default:'Successful'},createdAt:{type:Date,default:Date.now}},{_id:false});
const userSchema=new mongoose.Schema({name:String,email:{type:String,unique:true,lowercase:true},passwordHash:String,password:String,country:{type:String,default:'Kenya'},verified:{type:Boolean,default:true},balance:{type:Number,default:2450},card:{brand:String,last4:String,expiry:String,name:String},history:[transaction]});
const User=mongoose.model('User',userSchema);app.use(express.json());app.use(express.static(__dirname));
const safe=u=>({name:u.name,email:u.email,country:u.country,verified:u.verified,balance:u.balance,card:u.card,history:u.history});const issue=u=>jwt.sign({id:u.id},SECRET,{expiresIn:'7d'});
async function auth(req,res,next){try{let t=req.headers.authorization?.replace('Bearer ','');req.user=await User.findById(jwt.verify(t,SECRET).id);if(!req.user)throw 0;next()}catch{res.status(401).json({message:'Please sign in again.'})}}
app.post('/api/register',async(req,res)=>{try{let {name,email,password,country}=req.body;if(!name||!email||!password||password.length<6)return res.status(400).json({message:'Enter a name, email and 6+ character password.'});if(await User.findOne({email:email.toLowerCase()}))return res.status(409).json({message:'An account already exists with this email. Please sign in.'});let u=await User.create({name,email:email.toLowerCase(),passwordHash:await bcrypt.hash(password,12),country});res.json({token:issue(u),user:safe(u)})}catch{res.status(500).json({message:'Could not create your account. Please try again.'})}});
app.post('/api/login',async(req,res)=>{try{let u=await User.findOne({email:req.body.email?.toLowerCase()});let hash=u?.passwordHash||u?.password;if(!u||typeof hash!=='string'||!await bcrypt.compare(String(req.body.password||''),hash))return res.status(401).json({message:'Incorrect email or password.'});res.json({token:issue(u),user:safe(u)})}catch{res.status(500).json({message:'Could not sign in. Please try again.'})}});
app.get('/api/me',auth,(req,res)=>res.json(safe(req.user)));
app.post('/api/profile',auth,async(req,res)=>{let {name,country}=req.body;if(name)req.user.name=name.trim();if(country)req.user.country=country;await req.user.save();res.json(safe(req.user))});
app.post('/api/card',auth,async(req,res)=>{let {brand,last4,expiry,name}=req.body;if(!brand||!/^\d{4}$/.test(String(last4))||!expiry)return res.status(400).json({message:'Use card type, last four digits and expiry.'});req.user.card={brand,last4:String(last4),expiry,name:name||req.user.name};await req.user.save();res.json(safe(req.user))});
app.post('/api/transaction',auth,async(req,res)=>{let {type,amount,name,phone,country,received}=req.body,amountNumber=Number(amount);if(!['send','topup','withdraw'].includes(type)||!amountNumber||amountNumber<=0)return res.status(400).json({message:'Enter a valid amount.'});if(['send','withdraw'].includes(type)&&amountNumber>req.user.balance)return res.status(400).json({message:'Insufficient wallet balance.'});if(type==='withdraw'&&!req.user.card)return res.status(400).json({message:'Link a card before withdrawing.'});let t={id:'FS-'+crypto.randomBytes(5).toString('hex').toUpperCase(),type,name:type==='send'?name:type==='topup'?'Wallet top up':'Withdrawal to card',phone:type==='send'?phone:'',country:country||'',detail:type==='send'?`Sent to ${country}`:type==='topup'?`Added from ${req.user.card?.brand||'linked card'}`:`To ${req.user.card.brand} •••• ${req.user.card.last4}`,amount:type==='topup'?amountNumber:-amountNumber,received,status:'Successful',createdAt:new Date()};req.user.balance+=t.amount;req.user.history.unshift(t);await req.user.save();res.json({user:safe(req.user),transaction:t})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));mongoose.connect(URI).then(()=>app.listen(PORT,'0.0.0.0',()=>console.log('FlowSend running'))).catch(e=>{console.error(e);process.exit(1)});
